"""Test blueprint -- adds test coverage for existing code.

Steps:
  1. [CODE]  Create worktree on new branch
  2. [AGENT] Analyze: find untested or under-tested code
  3. [AGENT] Write tests
  4. [CODE]  Lint
  5. [CODE]  Run tests to verify they pass
  6. [AGENT] Fix any failing tests (up to max_rounds)
  7. [CODE]  Commit, push, create PR
"""

from __future__ import annotations

import time
from pathlib import Path

from minion.blueprints.base import (
    BlueprintResult,
    StepResult,
    StepType,
    format_step_log,
    run_shell,
)
from minion.blueprints.fix import run_agent_step
from minion.config import MinionConfig, detect_stack
from minion.prefetch import format_context_block, prefetch_context
from minion.worktree import Worktree


async def run_test_blueprint(
    target: str,
    repo_path: str,
    task_id: str,
    config: MinionConfig,
) -> BlueprintResult:
    """Execute the test blueprint. Target can be a file, directory, or description."""
    result = BlueprintResult(success=False)
    start = time.time()
    repo = Path(repo_path)
    branch = f"{config.repo.branch_prefix}tests-{task_id}"
    result.branch = branch

    tools = detect_stack(repo)
    if config.tools.test_cmd:
        tools.test_cmd = config.tools.test_cmd
    if config.tools.lint_cmd:
        tools.lint_cmd = config.tools.lint_cmd

    wt = Worktree(repo, branch, config.repo.base_branch)
    try:
        wt_path = wt.create()
    except Exception as e:
        result.steps.append(StepResult(success=False, output=str(e)))
        return result
    working_dir = str(wt_path)

    try:
        # Step 2 [CODE]: Prefetch context
        ctx = prefetch_context(target, repo_path, command="test")
        context_block = format_context_block(ctx)
        prefetch_info = f"{len(ctx.relevant_files)} files, {len(ctx.rules)} rules"
        print(format_step_log(2, StepType.DETERMINISTIC, f"Prefetch context ({prefetch_info})", StepResult(success=True)))

        # Step 3 [AGENT]: Analyze and write tests
        prompt = (
            f"{context_block}"
            f"Target: {target}\n\n"
            "Instructions:\n"
            "1. Explore the target code to understand its behavior\n"
            "2. Check what tests already exist for it\n"
            "3. Write thorough tests covering:\n"
            "   - Happy path / normal operation\n"
            "   - Edge cases (empty input, boundary values, null/None)\n"
            "   - Error conditions and exception handling\n"
            "4. Follow existing test patterns and conventions in the repo\n"
            "5. Use descriptive test names\n"
            "6. One assertion per test where practical"
        )
        step, session_id = await run_agent_step(prompt, working_dir, config)
        result.steps.append(step)
        result.session_id = session_id
        print(format_step_log(3, StepType.AGENT, "Write tests", step))

        # Step 4 [CODE]: Lint
        if tools.lint_cmd:
            lint_result = run_shell(tools.lint_cmd, working_dir)
            result.steps.append(lint_result)
            print(format_step_log(4, StepType.DETERMINISTIC, "Lint", lint_result))

        # Step 5 [CODE]: Run tests + feedback loop
        if tools.test_cmd:
            for round_num in range(config.max_rounds):
                test_result = run_shell(tools.test_cmd, working_dir, timeout=300)
                result.steps.append(test_result)
                print(format_step_log(5, StepType.DETERMINISTIC, f"Tests (round {round_num + 1})", test_result))

                if test_result.success:
                    break

                if round_num < config.max_rounds - 1:
                    fix_prompt = (
                        f"Tests failed:\n\n{test_result.output[:2000]}\n\n"
                        "Fix the failing tests. Do not delete tests to make them pass."
                    )
                    fix_step, session_id = await run_agent_step(
                        fix_prompt, working_dir, config, session_id,
                    )
                    result.steps.append(fix_step)
                    print(format_step_log(5, StepType.AGENT, f"Fix tests (round {round_num + 1})", fix_step))

        # Step 6 [CODE]: Commit, push, PR
        committed = wt.commit_and_push(f"test: add tests for {target[:60]}")
        if committed and config.github.create_pr:
            pr_url = wt.create_pr(
                title=f"test: add coverage for {target[:60]}",
                body=f"## Agent-generated tests\n\n**Target:** {target}\n\nGenerated by minion.",
                reviewer=config.github.reviewer,
            )
            result.pr_url = pr_url
            if pr_url:
                print(f"  PR: {pr_url}")

        result.success = True

    finally:
        result.total_duration = time.time() - start
        if not result.success:
            wt.cleanup()

    return result
